/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
    'payload-mcp-api-keys': PayloadMcpApiKeyAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    portfolio: Portfolio;
    insights: Insight;
    capabilities: Capability;
    people: Person;
    'payload-mcp-api-keys': PayloadMcpApiKey;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    portfolio: PortfolioSelect<false> | PortfolioSelect<true>;
    insights: InsightsSelect<false> | InsightsSelect<true>;
    capabilities: CapabilitiesSelect<false> | CapabilitiesSelect<true>;
    people: PeopleSelect<false> | PeopleSelect<true>;
    'payload-mcp-api-keys': PayloadMcpApiKeysSelect<false> | PayloadMcpApiKeysSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'main-menu': MainMenu;
  };
  globalsSelect: {
    'main-menu': MainMenuSelect<false> | MainMenuSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User | PayloadMcpApiKey;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
export interface PayloadMcpApiKeyAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  status?: ('draft' | 'published') | null;
  layout?:
    | (
        | {
            heading: string;
            headingHighlight: string;
            description: string;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            videoPoster?: string | null;
            videoUrl?: string | null;
            triangleImage?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            label: string;
            labelHighlight?: string | null;
            logos?:
              | {
                  url: string;
                  width?: number | null;
                  height?: number | null;
                  alt?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logoMarquee';
          }
        | {
            title: string;
            titleHighlight?: string | null;
            description: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'whatWeDo';
          }
        | {
            services?:
              | {
                  serviceKey: 'website' | 'ads' | 'crm';
                  title: string;
                  color: string;
                  features?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  ctaLabel?: string | null;
                  ctaUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'serviceTriangle';
          }
        | {
            title: string;
            titleHighlight?: string | null;
            items?:
              | {
                  title: string;
                  imageUrl: string;
                  imageWidth?: number | null;
                  imageHeight?: number | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'problems';
          }
        | {
            categories?:
              | {
                  title: string;
                  stats?:
                    | {
                        value: string;
                        label: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'metrics';
          }
        | {
            title: string;
            titleHighlight?: string | null;
            subtitle: string;
            subtitleHighlight?: string | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'workWithUs';
          }
        | {
            title: string;
            titleHighlight?: string | null;
            clutchLogoUrl?: string | null;
            reviews?:
              | {
                  rating?: number | null;
                  text: string;
                  author: string;
                  position?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            title: string;
            titleHighlight?: string | null;
            intro?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            rows?:
              | {
                  label: string;
                  color: string;
                  logos?:
                    | {
                        url: string;
                        width?: number | null;
                        height?: number | null;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'technology';
          }
        | {
            title: string;
            titleHighlight?: string | null;
            /**
             * Pull projects from the Portfolio collection instead of manual entries
             */
            useCollection?: boolean | null;
            collectionLimit?: number | null;
            /**
             * Optional: pick specific projects. Leave empty to show the latest published items.
             */
            selectedProjects?: (number | Portfolio)[] | null;
            projects?:
              | {
                  title: string;
                  year?: string | null;
                  services?: string | null;
                  imageUrl?: string | null;
                  url?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'portfolio';
          }
        | {
            title: string;
            titleHighlight?: string | null;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            imageUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'whoWeAre';
          }
        | {
            title: string;
            titleHighlight?: string | null;
            /**
             * Pull posts from the Insights collection instead of manual entries
             */
            useCollection?: boolean | null;
            collectionLimit?: number | null;
            /**
             * Optional: pick specific posts. Leave empty to show the latest published items.
             */
            selectedPosts?: (number | Insight)[] | null;
            posts?:
              | {
                  title: string;
                  excerpt?: string | null;
                  date?: string | null;
                  url?: string | null;
                  imageUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'insights';
          }
        | {
            title: string;
            titleHighlight?: string | null;
            subtitle?: string | null;
            variant?: ('dark' | 'light') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'pageBanner';
          }
        | {
            title: string;
            titleHighlight?: string | null;
            bodyHtml: string;
            phone?: string | null;
            phoneTel?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            hubspotPortalId?: string | null;
            hubspotFormId?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contactSection';
          }
        | {
            eyebrow?: string | null;
            title?: string | null;
            bodyHtml: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'richContent';
          }
        | {
            title?: string | null;
            titleHighlight?: string | null;
            /**
             * Pull top-level capabilities from the Capabilities collection
             */
            useCollection?: boolean | null;
            /**
             * Optional: pick specific capabilities. Leave empty to show all top-level items.
             */
            selectedCapabilities?: (number | Capability)[] | null;
            items?:
              | {
                  title: string;
                  description?: string | null;
                  url?: string | null;
                  color?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'capabilitiesGrid';
          }
        | {
            title: string;
            intro?: string | null;
            leadershipTitle?: string | null;
            leadershipIntro?: string | null;
            /**
             * Pull leaders from the People collection
             */
            useCollection?: boolean | null;
            /**
             * Optional: pick specific people. Leave empty to show all marked as leaders.
             */
            selectedPeople?: (number | Person)[] | null;
            leaders?:
              | {
                  name: string;
                  role: string;
                  imageUrl?: string | null;
                  id?: string | null;
                }[]
              | null;
            teamSizeTitle?: string | null;
            teamSizeDescription?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'teamSection';
          }
        | {
            title: string;
            description?: string | null;
            ctaLabel?: string | null;
            ctaUrl?: string | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'ctaBanner';
          }
        | {
            heading: string;
            ctaLabel: string;
            ctaUrl: string;
            id?: string | null;
            blockName?: string | null;
            blockType: 'callToAction';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio".
 */
export interface Portfolio {
  id: number;
  title: string;
  slug: string;
  status?: ('draft' | 'published') | null;
  client?: string | null;
  projectName?: string | null;
  /**
   * Project timeline or year
   */
  year?: string | null;
  services?: string | null;
  industry?: string | null;
  categories?: string | null;
  imageUrl?: string | null;
  /**
   * Public URL for this project
   */
  url?: string | null;
  heroHeading?: string | null;
  heroDescription?: string | null;
  summaryHtml?: string | null;
  featured?: boolean | null;
  wpId?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights".
 */
export interface Insight {
  id: number;
  title: string;
  slug: string;
  status?: ('draft' | 'published') | null;
  excerpt?: string | null;
  /**
   * Write with the visual editor. Use / or the + menu to insert blocks — including Call To Action (Trusted Advisors banner), callout, quote, CTA button, or image.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bodyHtml?: string | null;
  publishedDate?: string | null;
  imageUrl?: string | null;
  /**
   * Related capability slug from live site
   */
  capabilityTag?: string | null;
  url?: string | null;
  wpId?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capabilities".
 */
export interface Capability {
  id: number;
  title: string;
  slug: string;
  /**
   * Public URL path without leading slash, e.g. capabilities/demand-generation/lead-generation
   */
  path?: string | null;
  status?: ('draft' | 'published') | null;
  description?: string | null;
  /**
   * Accent color e.g. #EFB155
   */
  color?: string | null;
  imageUrl?: string | null;
  /**
   * Parent capability for nested pages
   */
  parent?: (number | null) | Capability;
  /**
   * Original WordPress URL (optional)
   */
  url?: string | null;
  /**
   * Write with the visual editor. Use / or the + menu to insert blocks — including Call To Action (Trusted Advisors banner), callout, quote, CTA button, or image.
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  bodyHtml?: string | null;
  wpId?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people".
 */
export interface Person {
  id: number;
  name: string;
  slug: string;
  status?: ('draft' | 'published') | null;
  role?: string | null;
  imageUrl?: string | null;
  bioHtml?: string | null;
  linkedinUrl?: string | null;
  mantra?: string | null;
  isLeader?: boolean | null;
  sortOrder?: number | null;
  url?: string | null;
  wpId?: number | null;
  meta?: {
    title?: string | null;
    description?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * API keys control which collections, resources, tools, and prompts MCP clients can access
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys".
 */
export interface PayloadMcpApiKey {
  id: number;
  /**
   * The user that the API key is associated with.
   */
  user: number | User;
  /**
   * A useful label for the API key.
   */
  label?: string | null;
  /**
   * The purpose of the API key.
   */
  description?: string | null;
  pages?: {
    /**
     * Allow clients to find pages.
     */
    find?: boolean | null;
    /**
     * Allow clients to create pages.
     */
    create?: boolean | null;
    /**
     * Allow clients to update pages.
     */
    update?: boolean | null;
  };
  portfolio?: {
    /**
     * Allow clients to find portfolio.
     */
    find?: boolean | null;
    /**
     * Allow clients to create portfolio.
     */
    create?: boolean | null;
    /**
     * Allow clients to update portfolio.
     */
    update?: boolean | null;
  };
  insights?: {
    /**
     * Allow clients to find insights.
     */
    find?: boolean | null;
    /**
     * Allow clients to create insights.
     */
    create?: boolean | null;
    /**
     * Allow clients to update insights.
     */
    update?: boolean | null;
  };
  capabilities?: {
    /**
     * Allow clients to find capabilities.
     */
    find?: boolean | null;
    /**
     * Allow clients to create capabilities.
     */
    create?: boolean | null;
    /**
     * Allow clients to update capabilities.
     */
    update?: boolean | null;
  };
  people?: {
    /**
     * Allow clients to find people.
     */
    find?: boolean | null;
    /**
     * Allow clients to create people.
     */
    create?: boolean | null;
    /**
     * Allow clients to update people.
     */
    update?: boolean | null;
  };
  media?: {
    /**
     * Allow clients to find media.
     */
    find?: boolean | null;
    /**
     * Allow clients to create media.
     */
    create?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  enableAPIKey?: boolean | null;
  apiKey?: string | null;
  apiKeyIndex?: string | null;
  collection: 'payload-mcp-api-keys';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'portfolio';
        value: number | Portfolio;
      } | null)
    | ({
        relationTo: 'insights';
        value: number | Insight;
      } | null)
    | ({
        relationTo: 'capabilities';
        value: number | Capability;
      } | null)
    | ({
        relationTo: 'people';
        value: number | Person;
      } | null)
    | ({
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      } | null);
  globalSlug?: string | null;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user:
    | {
        relationTo: 'users';
        value: number | User;
      }
    | {
        relationTo: 'payload-mcp-api-keys';
        value: number | PayloadMcpApiKey;
      };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  layout?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              headingHighlight?: T;
              description?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              videoPoster?: T;
              videoUrl?: T;
              triangleImage?: T;
              id?: T;
              blockName?: T;
            };
        logoMarquee?:
          | T
          | {
              label?: T;
              labelHighlight?: T;
              logos?:
                | T
                | {
                    url?: T;
                    width?: T;
                    height?: T;
                    alt?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        whatWeDo?:
          | T
          | {
              title?: T;
              titleHighlight?: T;
              description?: T;
              id?: T;
              blockName?: T;
            };
        serviceTriangle?:
          | T
          | {
              services?:
                | T
                | {
                    serviceKey?: T;
                    title?: T;
                    color?: T;
                    features?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    ctaLabel?: T;
                    ctaUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        problems?:
          | T
          | {
              title?: T;
              titleHighlight?: T;
              items?:
                | T
                | {
                    title?: T;
                    imageUrl?: T;
                    imageWidth?: T;
                    imageHeight?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        metrics?:
          | T
          | {
              categories?:
                | T
                | {
                    title?: T;
                    stats?:
                      | T
                      | {
                          value?: T;
                          label?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        workWithUs?:
          | T
          | {
              title?: T;
              titleHighlight?: T;
              subtitle?: T;
              subtitleHighlight?: T;
              description?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              title?: T;
              titleHighlight?: T;
              clutchLogoUrl?: T;
              reviews?:
                | T
                | {
                    rating?: T;
                    text?: T;
                    author?: T;
                    position?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        technology?:
          | T
          | {
              title?: T;
              titleHighlight?: T;
              intro?: T;
              rows?:
                | T
                | {
                    label?: T;
                    color?: T;
                    logos?:
                      | T
                      | {
                          url?: T;
                          width?: T;
                          height?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        portfolio?:
          | T
          | {
              title?: T;
              titleHighlight?: T;
              useCollection?: T;
              collectionLimit?: T;
              selectedProjects?: T;
              projects?:
                | T
                | {
                    title?: T;
                    year?: T;
                    services?: T;
                    imageUrl?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        whoWeAre?:
          | T
          | {
              title?: T;
              titleHighlight?: T;
              description?: T;
              imageUrl?: T;
              id?: T;
              blockName?: T;
            };
        insights?:
          | T
          | {
              title?: T;
              titleHighlight?: T;
              useCollection?: T;
              collectionLimit?: T;
              selectedPosts?: T;
              posts?:
                | T
                | {
                    title?: T;
                    excerpt?: T;
                    date?: T;
                    url?: T;
                    imageUrl?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        pageBanner?:
          | T
          | {
              title?: T;
              titleHighlight?: T;
              subtitle?: T;
              variant?: T;
              id?: T;
              blockName?: T;
            };
        contactSection?:
          | T
          | {
              title?: T;
              titleHighlight?: T;
              bodyHtml?: T;
              phone?: T;
              phoneTel?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              hubspotPortalId?: T;
              hubspotFormId?: T;
              id?: T;
              blockName?: T;
            };
        richContent?:
          | T
          | {
              eyebrow?: T;
              title?: T;
              bodyHtml?: T;
              id?: T;
              blockName?: T;
            };
        capabilitiesGrid?:
          | T
          | {
              title?: T;
              titleHighlight?: T;
              useCollection?: T;
              selectedCapabilities?: T;
              items?:
                | T
                | {
                    title?: T;
                    description?: T;
                    url?: T;
                    color?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        teamSection?:
          | T
          | {
              title?: T;
              intro?: T;
              leadershipTitle?: T;
              leadershipIntro?: T;
              useCollection?: T;
              selectedPeople?: T;
              leaders?:
                | T
                | {
                    name?: T;
                    role?: T;
                    imageUrl?: T;
                    id?: T;
                  };
              teamSizeTitle?: T;
              teamSizeDescription?: T;
              id?: T;
              blockName?: T;
            };
        ctaBanner?:
          | T
          | {
              title?: T;
              description?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
        callToAction?:
          | T
          | {
              heading?: T;
              ctaLabel?: T;
              ctaUrl?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "portfolio_select".
 */
export interface PortfolioSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  client?: T;
  projectName?: T;
  year?: T;
  services?: T;
  industry?: T;
  categories?: T;
  imageUrl?: T;
  url?: T;
  heroHeading?: T;
  heroDescription?: T;
  summaryHtml?: T;
  featured?: T;
  wpId?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "insights_select".
 */
export interface InsightsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  status?: T;
  excerpt?: T;
  content?: T;
  bodyHtml?: T;
  publishedDate?: T;
  imageUrl?: T;
  capabilityTag?: T;
  url?: T;
  wpId?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "capabilities_select".
 */
export interface CapabilitiesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  path?: T;
  status?: T;
  description?: T;
  color?: T;
  imageUrl?: T;
  parent?: T;
  url?: T;
  content?: T;
  bodyHtml?: T;
  wpId?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "people_select".
 */
export interface PeopleSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  status?: T;
  role?: T;
  imageUrl?: T;
  bioHtml?: T;
  linkedinUrl?: T;
  mantra?: T;
  isLeader?: T;
  sortOrder?: T;
  url?: T;
  wpId?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-mcp-api-keys_select".
 */
export interface PayloadMcpApiKeysSelect<T extends boolean = true> {
  user?: T;
  label?: T;
  description?: T;
  pages?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  portfolio?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  insights?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  capabilities?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  people?:
    | T
    | {
        find?: T;
        create?: T;
        update?: T;
      };
  media?:
    | T
    | {
        find?: T;
        create?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  enableAPIKey?: T;
  apiKey?: T;
  apiKeyIndex?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Site navigation shown in the header (mmenu). Supports up to 3 levels.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu".
 */
export interface MainMenu {
  id: number;
  /**
   * Top-level items (Capabilities, Industries, Insights, Our Team, Our Portfolio).
   */
  items?:
    | {
        label: string;
        /**
         * Use # for parent items that only open a submenu.
         */
        url?: string | null;
        children?:
          | {
              label: string;
              /**
               * Use # for parent items that only open a submenu.
               */
              url?: string | null;
              /**
               * Third-level links under this child.
               */
              links?:
                | {
                    label: string;
                    /**
                     * Use # for parent items that only open a submenu.
                     */
                    url?: string | null;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-menu_select".
 */
export interface MainMenuSelect<T extends boolean = true> {
  items?:
    | T
    | {
        label?: T;
        url?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              links?:
                | T
                | {
                    label?: T;
                    url?: T;
                    id?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InsightCallToActionBlock".
 */
export interface InsightCallToActionBlock {
  /**
   * Large heading inside the cyan CTA box (matches live insight pages).
   */
  heading: string;
  ctaLabel: string;
  ctaUrl: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'insightCallToAction';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}